name: github-action-trigger-workflow
description: Triggers another workflows and wait
author: datavisyn

inputs:
  owner:
    description: "The owner of the repository where the workflow is contained."
    required: true
  repo:
    description: "The repository where the workflow is contained."
    required: true
  github_token:
    description: "The Github access token with access to the repository. It is recommended you put this token under secrets."
    required: true
  github_user:
    description: "The name of the github user whose access token is being used to trigger the workflow."
    required: false
  ref:
    description: 'The reference of the workflow run. The reference can be a branch, tag, or a commit SHA. Default: main'
    required: false
  wait_interval:
    description: "The number of seconds delay between checking for result of run."
    required: false
  workflow_file_name:
    description: "The reference point. For example, you could use main.yml."
    required: true
  client_payload:
    description: 'Payload to pass to the workflow, must be a JSON string'
    required: false
  propagate_failure:
    description: 'Fail current job if downstream job fails. default: true'
    required: false
  trigger_workflow:
    description: 'Trigger the specified workflow. default: true'
    required: false
  wait_workflow:
    description: 'Wait for workflow to finish. default: true'
    required: false
  comment_downstream_url:
    description: 'A comments API URL to comment the current downstream job URL to. Default: no comment'
    required: false
  comment_github_token:
    description: 'token used for pull_request comments'
    required: false
    default: ${{github.token}}
outputs:
  workflow_id:
    description: The ID of the workflow that was triggered by this action
  workflow_url:
    description: The URL of the workflow that was triggered by this action
  conclusion:
    description: The conclusion of the workflow that was triggered by this action
runs:
  using: 'docker'
  image: 'Dockerfile'
